title: "natan ou natan?"
email: natanounatan@gmail.com
description: "trying to be better than yesterday"
baseurl: "/"
url: "natanounatan.github.io"
twitter_username: natanounatan
github_username: natanounatan

permalink: /:title
