title: "natan ou natan?"
email: natanounatan@gmail.com
description: "tentando ser melhor do que ontem"
baseurl: ""
url: "https://natansiqueira.com"
google_analytics: G-ZZ4YLH7SLH

twitter:
  username: natanounatan
  card: summary

permalink: /:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
